coreos/coreos-kubernetes

Documentation/configure-kubectl.md
Documentation/deploy-addons.md
Documentation/deploy-master-single.md
Documentation/deploy-workers.md
Documentation/getting-started.md

editor's autocomplete sucks...

docs: fix markup

---

README.md

This is an attempt at incorporating @polvi's original PR (#12) into master.

README: the CoreOS way

---

Documentation/kubernetes-on-vagrant-single.md

Documentation: Fix IP addrs used in kubectl config

---

Documentation/getting-started.md

Fixes https://github.com/coreos/coreos-kubernetes/issues/41

docs: set listen interface for single node etcd

---

Documentation/kubernetes-on-vagrant-single.md

docs: tiny typo fix

---

Documentation/configure-kubectl.md
Documentation/deploy-master-single.md
Documentation/deploy-workers.md
Documentation/kubernetes-on-vagrant-single.md
Documentation/kubernetes-on-vagrant.md
multi-node/generic/controller-install.sh
multi-node/generic/worker-install.sh
single-node/user-data

Kubernetes v1.0.6 is ready to rock

docs: update to Kubernetes v1.0.6

---

Documentation/conformance-tests.md
README.md

/cc @robszumski anywhere in particular you want this linked?

docs: conformance tests

---

Documentation/configure-kubectl.md
Documentation/deploy-master.md
Documentation/deploy-workers.md
Documentation/getting-started.md
Documentation/openssl.md

/cc @bcwaldon @polvi @robszumski

HA documentation

---

Documentation/kubernetes-on-aws.md
README.md

I found some typos. Please review.
And thanks for the great documentation!

README, Documentation: fix typos

---

Documentation/configure-kubectl.md
Documentation/deploy-addons.md
Documentation/deploy-master.md
Documentation/deploy-workers.md
Documentation/getting-started.md
Documentation/openssl.md

* Moved up 'hostNetwork: true' inside kube-controller-manager yaml
* Added note for keys' permissions
* Added info about VIP addreses
* Added CoreOS release requirement into the top of README.md
* Updated curl api response to v1.0.6
/cc @robszumski

Fixed Kubernetes docs

---

Documentation/deploy-master.md
Documentation/deploy-workers.md
Documentation/kubernetes-networking.md
Documentation/kubernetes-on-baremetal.md
README.md

/cc @robszumski @joshix @brianredbeard

Baremetal & Networking docs

---

Documentation/kubernetes-networking.md

Not much to say, I just stumbled upon this broken link...

kubernetes-networking.md: fixed broken link

---

Documentation/deploy-master.md

1. Explain why master node kubelet is configured with register-node=FALSE
2. Explain api comm fail warnings in kubelet logs on master nodes per #1, above.
3. Bump every heading up one level (naive correction of heading hierarchy)
Fixes https://github.com/coreos-inc/design/issues/165, https://github.com/coreos/coreos-kubernetes/issues/56, https://github.com/coreos/coreos-kubernetes/issues/111

Documentation/deploy-master: Explain register-node=0

---

Documentation/deploy-addons.md
Documentation/deploy-master.md
Documentation/kubernetes-networking.md
Documentation/kubernetes-on-baremetal.md
Documentation/kubernetes-on-vagrant-single.md
Documentation/kubernetes-on-vagrant.md
README.md

docs: change k8s links to v1.1

---

contrib/publish-release.sh
multi-node/aws/build

Fixes for publishing custom releases

---

Documentation/kubernetes-upgrade.md

/cc @robszumski @joshix @bcwaldon

docs: Upgrading k8s components

---

Documentation/conformance-tests.md
Documentation/deploy-master.md
Documentation/deploy-workers.md
multi-node/aws/artifacts/scripts/install-controller.sh
multi-node/aws/artifacts/scripts/install-worker.sh
multi-node/aws/pkg/cluster/stack_template.go
multi-node/generic/controller-install.sh
multi-node/generic/worker-install.sh
single-node/user-data

Fixes https://github.com/coreos/coreos-kubernetes/issues/82

Use default cAdvisor settings

---

multi-node/aws/artifacts/scripts/install-worker.sh

set cloud-provider=aws on aws worker kubelet

---

multi-node/aws/pkg/cluster/stack_template.go

allow icmp destination unreachable

---

Documentation/configure-kubectl.md
Documentation/kubernetes-on-vagrant-single.md
Documentation/kubernetes-on-vagrant.md

Fixes #201.
Additional quick style-type fixes. Headings.

Documentation/kubectl: Clarify kubectl download instructions

---

Documentation/kubernetes-on-baremetal.md

docs: fix html typo

---

Documentation/deploy-master.md

When I was walking though this the first time, was not sure if that directory should have already existed. I am adding this to call out this step.

Specificity required during ssl step

---

MAINTAINERS

MAINTAINERS: add colin.hom@coreos.com

---

multi-node/aws/artifacts/manifests/controller/kube-apiserver.yaml
multi-node/generic/controller-install.sh
single-node/user-data

Fixes https://github.com/coreos/coreos-kubernetes/issues/237

k8s: enable deployment and daemonset extension APIs

---

multi-node/aws/artifacts/manifests/controller/kube-apiserver.yaml
multi-node/generic/controller-install.sh
single-node/user-data

NamespaceExists functionality rolled into NamespaceLifecycle.
See: http://kubernetes.io/v1.1/docs/admin/admission-controllers.html

k8s: Update admission-control list to 1.1 recs

---

multi-node/vagrant/Vagrantfile

multi-node: remove unused variable

---

Documentation/kubernetes-on-aws.md

I think your markdown needs to be formatted in this way, so that list contents aren't treated as code blocks (and contained formatting is applied, e.g. hyperlinks).

Fix formatting

---

multi-node/aws/build

it now sets up the gopath for you

kube-aws: improved build script

---

Documentation/getting-started.md

Doc/getting-started: Tweak link to TLS cert generation document

---

Documentation/configure-kubectl.md
Documentation/deploy-master.md
Documentation/deploy-workers.md
Documentation/kubelet-wrapper.md
Documentation/kubernetes-on-vagrant-single.md
Documentation/kubernetes-on-vagrant.md
Documentation/kubernetes-upgrade.md
multi-node/aws/artifacts/scripts/install-controller.sh
multi-node/aws/artifacts/scripts/install-worker.sh
multi-node/generic/controller-install.sh
multi-node/generic/worker-install.sh
single-node/user-data

k8s: bump version to v1.1.8

---

Documentation/kubernetes-on-aws.md

Completes/fixes https://github.com/coreos/coreos-kubernetes/pull/301
cc: @aaronlevy

docs: convert to paragraph from list

---

Documentation/kubelet-wrapper.md

kubelet-wrapper.md: Unindent yaml block

---

Documentation/kubelet-wrapper.md

Documentation: fix typo

---

Documentation/conformance-tests.md

Fixes https://github.com/coreos/coreos-kubernetes/issues/308
cc: @aaronlevy @rutsky

docs: update conformance instructions

---

Documentation/deploy-master.md
Documentation/deploy-workers.md
Documentation/kubelet-wrapper.md
multi-node/aws/pkg/config/templates/cloud-config-controller
multi-node/aws/pkg/config/templates/cloud-config-worker
multi-node/generic/controller-install.sh
multi-node/generic/worker-install.sh
single-node/user-data

following up from https://github.com/coreos/coreos-kubernetes/pull/314

Documentation: use new style api-server flag

---

multi-node/aws/pkg/config/config.go
multi-node/aws/pkg/config/config_test.go
multi-node/aws/pkg/config/templates/cloud-config-controller
multi-node/aws/pkg/config/templates/cloud-config-worker
multi-node/aws/pkg/config/tls_config.go
multi-node/aws/pkg/config/user_data_config_test.go

The tls compaction codepath does not behave conditionally on Config.KmsKeyARN being set.
\cc @aaronlevy

kube-aws: stub out kms encryption interface

---

multi-node/aws/pkg/config/config.go
multi-node/aws/pkg/config/config_test.go

kube-aws: fix cidr conflict validation

---

Documentation/kubernetes-on-aws.md
multi-node/aws/README.md

kube-aws: explicit AWS credentials instructions

---

multi-node/aws/build

kube-aws: fix build script version flag

---

Documentation/deploy-master.md
multi-node/aws/pkg/config/templates/cloud-config-controller
multi-node/generic/controller-install.sh
single-node/user-data

Based on https://github.com/coreos/coreos-kubernetes/pull/319/files.

all: curl commands to avoid breakage in 1.2

---

Documentation/deploy-addons.md
Documentation/kubernetes-on-vagrant-single.md
Documentation/kubernetes-on-vagrant.md

Completes fixes needed for https://github.com/coreos/coreos-kubernetes/pull/323

docs: fix broken Guestbook link

---

multi-node/aws/cmd/kube-aws/main.go

kube-aws: fix duplicate error printouts

---

multi-node/aws/pkg/config/config.go

When editing the cloudformation JSON, syntax errors can be very hard to track down based on the error message from the JSON parser alone.
SyntaxError does provide a byte offset, which is now used to show a few lines of context surrounding the location in the JSON document where the error occurred.

kube-aws: improve cloudformation json validation

---

multi-node/aws/cmd/kube-aws/command_up.go

kube-aws: validate user data in `kube-aws up`

---

multi-node/aws/cmd/kube-aws/command_up.go

I've timed it several times with several cluster sizes and it's always
taken very close to 5 minutes.

kube-aws: be specific about how long resource creation takes.

---

Documentation/kubelet-wrapper.md

docs: Added an info about custom nameservers for the kubelet wrapper

---

Documentation/deploy-master.md

Documentation: Rephrase leader election/ha section for masters

---

Documentation/kubernetes-on-aws.md
multi-node/aws/README.md

kube-aws: update docs to reflect route53 integration

---

multi-node/aws/pkg/config/templates/cloud-config-controller

multi-node/aws: fix some bash logic

---

multi-node/aws/pkg/cluster/cluster_test.go
multi-node/aws/pkg/config/config.go
multi-node/aws/pkg/config/config_test.go

kube-aws: validate externalDNSName is a subdomain of hostedZone

---

Documentation/configure-kubectl.md

These look silly, so let's remove the backticks

docs: fix headers

---

multi-node/aws/pkg/cluster/cluster.go
multi-node/aws/pkg/cluster/cluster_test.go

Fixes #415 
\cc @aaronlevy @cgag @orkhanM

Testable stack creation

---

multi-node/aws/pkg/config/config.go
multi-node/aws/pkg/config/config_test.go
multi-node/aws/pkg/config/templates/cluster.yaml

kube-aws: configurable release channel

---

multi-node/aws/pkg/config/config.go

GoLint doesn't like valid() using "cfg" for its receiver when all
the other methods user "c".

kube-aws: golint: use same var for all cluster methods

---

Documentation/kubernetes-on-aws.md
Documentation/kubernetes-on-vagrant-single.md
Documentation/kubernetes-on-vagrant.md

Documentation: add note about cluster startup delay

---

Documentation/configure-kubectl.md
Documentation/conformance-tests.md
Documentation/deploy-master.md
Documentation/deploy-workers.md
Documentation/kubelet-wrapper.md
Documentation/kubernetes-on-aws.md
Documentation/kubernetes-on-vagrant-single.md
Documentation/kubernetes-on-vagrant.md
Documentation/kubernetes-upgrade.md
multi-node/aws/pkg/config/config.go
multi-node/aws/pkg/config/templates/cluster.yaml
multi-node/generic/controller-install.sh
multi-node/generic/worker-install.sh
single-node/user-data

/cc @colhom @pbx0 @derekparker 
One new flake: https://github.com/coreos/coreos-kubernetes/issues/380#issuecomment-218341729

*: Kubernetes v1.2.4

---

Documentation/deploy-master.md
Documentation/deploy-workers.md
Documentation/kubelet-wrapper.md
Documentation/kubernetes-on-aws.md
Documentation/kubernetes-on-vagrant.md
Documentation/kubernetes-upgrade.md
multi-node/aws/pkg/config/config.go
multi-node/aws/pkg/config/templates/cluster.yaml
multi-node/generic/controller-install.sh
multi-node/generic/worker-install.sh
single-node/user-data

Image release: https://github.com/coreos/kubernetes/releases/tag/v1.2.4%2Bcoreos.1
fixes https://github.com/coreos/coreos-kubernetes/issues/372 https://github.com/coreos/coreos-kubernetes/issues/327 https://github.com/kubernetes/kubernetes/issues/24767
/cc @robszumski @colhom 
Note: The release images are still building, so I'll wait to actually merge this until they're actually done building.

*: Bump v1.2.4+coreos.1

---

Documentation/kubernetes-on-aws.md

Ref coreos-inc/coreos-pages#691.

Documentation/k8s-on-aws: Fix headings and special chars

---

Documentation/deploy-master.md
Documentation/kubelet-wrapper.md

Adds docs to address use-cases in:
- Fixes https://github.com/coreos/coreos-kubernetes/issues/322
- Fixes https://github.com/coreos/coreos-kubernetes/issues/481
- Various folks on Kubernetes Slack

docs: expand customization options

---

multi-node/aws/build
multi-node/aws/build-release-binaries

scripts: add release script

---

Documentation/kubernetes-on-baremetal.md

Here is a first crack at adding links to coreos-baremetal...
@robszumski @joshix

Add coreos-baremetal to k8s guides

---

multi-node/aws/pkg/config/region_map.go

was needlessly complex due to oversight in the previous refactor.
also removed redundant and unecessary state about valid regions and supported channels. this information is now provided canonically by the coreos release ami metadata and the config package respectively.
\cc @cgag

config: clean up ami region/channel resolution code

---

multi-node/aws/pkg/config/config.go
multi-node/aws/pkg/config/config_test.go

Depends on #523 . the second commit is the content of this PR.
\cc @aaronlevy @cgag @pbx0

Stable channel is supported and default

---

Documentation/configure-kubectl.md

Add links to platforms for folks hitting this page directly from Google search results.

docs: add links to guides

---

Documentation/conformance-tests.md
Documentation/deploy-master.md
Documentation/deploy-workers.md
Documentation/kubelet-wrapper.md
Documentation/kubernetes-on-aws.md
Documentation/kubernetes-on-vagrant.md
Documentation/kubernetes-upgrade.md
contrib/bump-version.sh
contrib/conformance-test.sh
multi-node/aws/pkg/config/config.go
multi-node/aws/pkg/config/templates/cloud-config-controller
multi-node/aws/pkg/config/templates/cloud-config-worker
multi-node/aws/pkg/config/templates/cluster.yaml
multi-node/generic/controller-install.sh
multi-node/generic/worker-install.sh
multi-node/vagrant/conformance-test.sh
single-node/conformance-test.sh
single-node/user-data

This branch will continue to be updated until there is an official 1.3 release - but want to put it up for other's to start any initial validation / testing

v1.3 updates

---

Documentation/kubernetes-upgrade.md

docs: fix formatting

---

Documentation/deploy-master.md
Documentation/deploy-workers.md
Documentation/kubelet-wrapper.md
Documentation/kubernetes-upgrade.md
contrib/bump-version.sh
multi-node/aws/pkg/config/config.go
multi-node/aws/pkg/config/templates/cluster.yaml
multi-node/generic/controller-install.sh
multi-node/generic/worker-install.sh
single-node/user-data

\cc @aaronlevy @pbx0 
Conformance tests look good, after some flakes.

all: update hyperkube version to v1.3.2_coreos.0

---

multi-node/aws/containerized-build-release-binaries

aws: containerized build of release binaries

---

Documentation/deploy-addons.md
Documentation/kubernetes-on-vagrant-single.md
Documentation/kubernetes-on-vagrant.md

Changed link to 1.3 Guestbook sample

Guestbook link updated to 1.3

---

Documentation/kubelet-wrapper.md
Documentation/kubernetes-on-baremetal.md
Documentation/kubernetes-on-vagrant-single.md
Documentation/kubernetes-upgrade.md

Documentation: update remaining 1.2->1.3 version references

---

Documentation/kubernetes-on-generic-platforms.md
multi-node/generic/README.md

Supersedes https://github.com/coreos/coreos-kubernetes/pull/618
cc: @pbx0 @aaronlevy

Docs: add guide for generic platforms

---

Documentation/deploy-addons.md
Documentation/deploy-master.md
Documentation/deploy-workers.md
multi-node/aws/pkg/config/templates/cloud-config-controller
multi-node/generic/controller-install.sh
single-node/user-data

Happy to split into two PRs if we want to discuss any of this more, though I think it shouldn't be too bad to just discuss it all here.
cc @joshix @aaronlevy @pbx0

Update to the modern kube-dns; a few other minor tweaks

---

Documentation/kubernetes-on-aws-render.md
multi-node/aws/pkg/config/config.go
multi-node/vagrant/Vagrantfile
single-node/Vagrantfile

docker2aci bug in v1.11 rkt is problematic, bump minimum OS version now that alpha is rkt v1.13

all: bump rktnetes min version

---

Documentation/kubernetes-on-aws-render.md

fixes #560 
\cc @robszumski @Thermus

aws: document multi-az / ebs / pv nuance

---

Documentation/kube-aws-users.md

Based on the things people put in here. https://github.com/coreos/coreos-kubernetes/issues/647

Documentation: add kube-aws users lists

---

multi-node/aws/cmd/kube-aws/command_render.go
multi-node/aws/pkg/config/config.go
multi-node/aws/pkg/config/templates/cluster.yaml
multi-node/aws/pkg/config/tls_config.go
multi-node/aws/pkg/tlsutil/x509.go

Implementation of my last comment in this thread: https://github.com/coreos/coreos-kubernetes/issues/621
Happy to change this as that thread forms more of a consensus. I don't feel too strongly about my stance on this interim state.
cc @aaronlevy

configure tls cert expiration

---

Documentation/deploy-master.md
Documentation/deploy-workers.md
Documentation/kubernetes-upgrade.md
multi-node/aws/pkg/config/templates/cloud-config-controller
multi-node/aws/pkg/config/templates/cloud-config-worker
multi-node/generic/controller-install.sh
multi-node/generic/worker-install.sh
single-node/user-data

Calico: Mount /etc/resolv.conf so DNS works

---

Documentation/deploy-master.md
Documentation/deploy-workers.md

docs: fix ref links

---

Documentation/getting-started.md
Documentation/kubernetes-on-generic-platforms.md

Fixes https://github.com/coreos/coreos-kubernetes/pull/677

docs: link to etcd clustering in containers

---

Documentation/kubernetes-on-aws.md
multi-node/aws/README.md

[kube-aws/docs] add survey link

---

contrib/conformance-test.sh

same as: https://github.com/kubernetes-incubator/bootkube/pull/153
fixes https://github.com/coreos/coreos-kubernetes/issues/692

contrib: get go-bindata for conformance test dep

---

Documentation/kubernetes-on-aws.md

Point to new location of kube-aws

---

Documentation/deploy-master.md

Fix link to Calico guide

---

Documentation/deploy-addons.md
Documentation/deploy-master.md
Documentation/kubernetes-networking.md
Documentation/kubernetes-upgrade.md
multi-node/generic/README.md

This fixes all broken links identified by
[marker](https://crates.io/crates/marker).

*: Fix broken links

---

Documentation/kubernetes-on-vagrant.md

sudo should be used to move kubectl under /usr/local/bin/

Added sudo to command, that moves kubectl

---

Documentation/getting-started.md

Plugging our fancy tool.
@joshix @philips

docs/getting-started: Tectonic for quick installs.
