single-node/Vagrantfile
tectonic-manager is unable to deploy with only 512MB b/c it ran out of
memory. Fix by increasing RAM.
=> single-node: use 1024 MB of RAM

Documentation/deploy-master-single.md
/cc @bcwaldon @philips 
This feels kinda hackish. Before updating this in the rest of the vagrant scripts, any thoughts on this approach?
=> docs: flannel config from location that survives restart

Documentation/deploy-addons.md
kube-system namespace creation was moved into the deploy-master step. Will get an error here if we try and create it again.
=> docs: kube-system namespace created prior to addon

Documentation/deploy-master-single.md, multi-node/generic/controller-install.sh, single-node/user-data
This was likely added by accident, and we don't see it
being necessary for the cluster to operate correctly.
=> *: remove unnecessary container port

Documentation/kubernetes-on-vagrant-single.md
Since the `cd foo` is in the previous section it was a bit unclear.
=> Documentation: clarify which dir to configure kubectl from

multi-node/generic/controller-install.sh, multi-node/generic/worker-install.sh, single-node/user-data
Changed this in documentation. This implements it in the vagrant bootstrap scripts.
=> bootstrap: link flannel conf from location surviving reboots

Documentation/configure-kubectl.md, Documentation/kubernetes-on-vagrant-single.md, Documentation/kubernetes-on-vagrant.md
Copying and pasting those commands neither worked on my mac or my CoreOS machine. The env var was not expanding.
=> Documentation: add missing semicolons in bash commands

Documentation/kubernetes-on-vagrant.md
Fixing a trivial typo in the docs.
=> `s/on/no/` in kubernetes-on-vagrant.md

Documentation/deploy-master.md, multi-node/generic/controller-install.sh, single-node/user-data
Fixes: https://github.com/coreos/coreos-kubernetes/issues/112
Ran k8s conformance tests. All worked well.
Leaving the aws installation as-is for now (using udp) because we are switching to use the cloud-provider/vpc integration soon anyway.
/cc @philips @eyakubovich
=> flannel: use vxlan backend

Documentation/kubernetes-on-aws.md
Cool tool! Thanks.
Running through the docs, looks like the `describe` command should be `status`.
=> documentation: s/describe/status/

multi-node/aws/pkg/cluster/stack_template.go
=> Use the correct AWS role when creating workers.

Documentation/configure-kubectl.md
Remove the overly specific mentions of "vagrant" in resource names in this general-purpose document. Specific vagrant documents exist.
Fixes https://github.com/coreos/coreos-kubernetes/issues/124
=> Documentation/configure-kubectl: s/vagrant/default/

multi-node/aws/cluster.yaml.example, multi-node/aws/pkg/cluster/cluster.go, multi-node/aws/pkg/cluster/config.go, multi-node/aws/pkg/cluster/stack_template.go
The current template defaults to 8 GiB root volumes with ~5 GiB of usable space with system overhead.
=> multi-node/aws: increase default volume size

multi-node/aws/cluster.yaml.example, multi-node/aws/pkg/cluster/cluster.go, multi-node/aws/pkg/cluster/config.go, multi-node/aws/pkg/cluster/stack_template.go
This allows users to configure the controller and worker instance types.
It also changes the config to use the aws defaults unless defined in the config and updates the supported channels to include beta.
Fixes #150 and possibly #154
=> multi-node/aws: expose more config options

Documentation/kubernetes-on-vagrant.md
=> Doc/kubernetes-on-vagrant: Distinguish kubectl download OS target

Documentation/deploy-workers.md, Documentation/getting-started.md, Documentation/openssl.md
Using per-worker TLS certificates/keys allows the SubjectAltNames to be
accurate for each worker node and increases security over
shared-certificate solutions like setting `\CN=*` and is more portable
to different cloud providers and on-prem installations than solutions
like using `*.ec2.internal` in the SAN. Sadly, doing this also adds
installation complexity. Having correct SAN settings on the workers allows
`kubectl exec` to work instead of giving TLS errors.
Fixes documentation part of
[#73](https://github.com/coreos/coreos-kubernetes/issues/73)
=> docs: create unique TLS certs per worker

multi-node/aws/pkg/cluster/stack_template.go
When using the AWS CloudFormation interface, the Availability Zone field is not marked optional.
> If not set, a zone will be chosen for you in the region being used to deploy the CloudFormation stack.
=> pkg/cluster: mark AZ choice as optional

Documentation/deploy-master.md
Assuming there will be another poor soul that will be confused... In retrospective, this seems obvious. But you never know.
*EDIT*: Oops! :droplet: In `getting-started` is stated _clearly_ that the syntaxis for `ETCD_ENDPOINTS` is `http://ip:port`. So, I'm not sure. Do we cancel the PR. or add this redundant note anyways?
*EDIT 2*: Modified on observation by @phemmer.
=> Add heads-up in replacement of variable when using curl

multi-node/aws/pkg/cluster/stack_template.go
needed by things such as kubernetes' heapser for auto-scaling
Fixes #177
=> multi-node/aws: allow access to kublet read-only port from worker SG

Documentation/deploy-master.md
A `drop-in` is explained at the `docker` item, right after the `flannel` one. Is desirable to give that explanation before.
=> Documentation: Explain what is a drop-in

multi-node/aws/artifacts/scripts/install-controller.sh, multi-node/aws/artifacts/scripts/install-worker.sh, multi-node/aws/cluster.yaml.example, multi-node/aws/cmd/kube-aws/command_up.go, multi-node/aws/pkg/cluster/cloud_config_controller.go, multi-node/aws/pkg/cluster/cloud_config_worker.go, multi-node/aws/pkg/cluster/cluster.go, multi-node/aws/pkg/cluster/config.go, multi-node/aws/pkg/cluster/stack_template.go
hardcodes kubernetes cidr as 10.0.0.0/8
exposes in cluster.yaml and validates on `up`:
- vpcCidr
- subnetCidr
- controllerIp
=> kube-aws: expose network configuration

multi-node/aws/pkg/cluster/config.go, multi-node/aws/pkg/cluster/config_test.go
make sure default network configuration values are applied to the configuration struct at parse time. the defaults were being validated if the supplied value is empty, but the default value was not being written back to the configuration struct.
this is important so that the inferred default values are set before
- the network toplogy is validated
- ssl certificates are generated
fixes #226
=> kube-aws: fix network defaults bug

Documentation/kubernetes-on-aws.md, multi-node/aws/artifacts/manifests/cluster/heapster-rc.json, multi-node/aws/artifacts/manifests/cluster/heapster-svc.json, multi-node/aws/artifacts/manifests/cluster/influxdb-rc.json, multi-node/aws/artifacts/manifests/cluster/influxdb-svc.json, multi-node/aws/artifacts/scripts/install-controller.sh, multi-node/generic/controller-install.sh, multi-node/vagrant/Vagrantfile, multi-node/vagrant/config.rb.sample, single-node/user-data
This change pulls in the heapster, influxdb, and grafana addons from Kubernetes and deploys them to the single node vagrant cluster by default. If the approach seems acceptable, I'll submit similar changes for our multi-node tools.
=> enable heapster and influxdb by default

Documentation/configure-kubectl.md, Documentation/deploy-master.md, Documentation/deploy-workers.md, Documentation/getting-started.md, Documentation/kubernetes-networking.md, Documentation/kubernetes-on-aws.md, Documentation/kubernetes-on-baremetal.md, Documentation/kubernetes-on-vagrant-single.md, Documentation/kubernetes-on-vagrant.md, Documentation/kubernetes-upgrade.md, Documentation/openssl.md
Added more details on the distinction between /srv/kubernetes and
/etc/kubernetes at the top of the master deployment instructions.
Updated docs to use "controller" instead of "master" to conform with
current terminology, and to use "node" to refer specifically to worker
nodes in most places.  (Variable names and directory path references
left unchanged to avoid inadvertently breaking other docs.)
Fixes #203
=> docs: add details on /srv vs. /etc; s/master/controller/ throughout

multi-node/aws/cluster.yaml.example, multi-node/aws/pkg/cluster/cluster.go, multi-node/aws/pkg/cluster/config.go, multi-node/aws/pkg/cluster/stack_template.go
I made the parameter a string, 'cause I'm scared about the floating-point math from YAML through Go to AWS. It appears to be a string in the AWS API, in any event.
=> kube-aws: add parameter for spot price

Documentation/getting-started.md
Currently the getting started guide has a very unclear hyperlink to instructions for generating TLS assets yourself. This PR introduces a more obvious link.
=> Improve link to OpenSSL instructions

Documentation/configure-kubectl.md, Documentation/deploy-master.md, Documentation/deploy-workers.md, Documentation/kubelet-wrapper.md, Documentation/kubernetes-on-baremetal.md, Documentation/kubernetes-on-vagrant-single.md, Documentation/kubernetes-on-vagrant.md, Documentation/kubernetes-upgrade.md, multi-node/aws/artifacts/manifests/controller/kube-apiserver.yaml, multi-node/aws/artifacts/manifests/controller/kube-controller-manager.yaml, multi-node/aws/artifacts/manifests/controller/kube-proxy.yaml, multi-node/aws/artifacts/manifests/controller/kube-scheduler.yaml, multi-node/aws/artifacts/manifests/worker/kube-proxy.yaml, multi-node/aws/artifacts/scripts/install-controller.sh, multi-node/aws/artifacts/scripts/install-worker.sh, multi-node/generic/controller-install.sh, multi-node/generic/worker-install.sh, single-node/user-data
/cc @robszumski @joshix for doc changes
=> k8s: Update deployments + docs to use hyperkube image and kubelet-wrapper

multi-node/aws/pkg/config/config.go, multi-node/aws/pkg/config/config_test.go, multi-node/aws/pkg/config/templates/cluster.yaml, multi-node/aws/pkg/config/tls_config.go
It is now cacluated from Cluster.ServiceCIDR, so it is now a member of the Config struct.
\cc @aaronlevy @ericchiang
=> kube-aws: kubernetesServiceIP is no longer a parameter.

Documentation/kubernetes-on-aws.md
Right now we have two stanzas that tell you how to configure credentials. I remove the first and kept the second since it has the two options instead of just env vars.
=> docs: remove duplicate credential step

Documentation/kubernetes-on-aws.md
Seems like this is a better location for this link. This gets you release notes, binaries, and an easy way to browse the project if you're interested.
=> docs: link to kube-aws releases

Documentation/kubernetes-on-aws.md, multi-node/aws/README.md
Throwing binaries on S3 is not advisable when we also have the github release tarballs as well, so we won't be doing that anymore.
=> kube-aws: installation instructions include GPG verification

multi-node/aws/pkg/cluster/cluster.go, multi-node/aws/pkg/cluster/cluster_test.go, multi-node/aws/pkg/config/config.go, multi-node/aws/pkg/config/config_test.go, multi-node/aws/pkg/config/templates/cluster.yaml, multi-node/aws/pkg/config/templates/stack-template.json, multi-node/aws/pkg/config/tls_config_test.go, multi-node/aws/pkg/config/user_data_config_test.go
I've added some validation as well so folks don't waste time creating clusters and tracking down subnet conflicts in the cloudformation events logs when the create fails.
=> Support for deploying to existing VPC

Documentation/configure-kubectl.md, Documentation/conformance-tests.md, Documentation/deploy-addons.md, Documentation/deploy-master.md, Documentation/deploy-workers.md, Documentation/kubelet-wrapper.md, Documentation/kubernetes-networking.md, Documentation/kubernetes-on-baremetal.md, Documentation/kubernetes-on-vagrant-single.md, Documentation/kubernetes-on-vagrant.md, Documentation/kubernetes-upgrade.md, multi-node/aws/README.md, multi-node/aws/pkg/config/config.go, multi-node/aws/pkg/config/templates/cloud-config-controller, multi-node/aws/pkg/config/templates/cloud-config-worker, multi-node/aws/pkg/config/templates/cluster.yaml, multi-node/generic/controller-install.sh, multi-node/generic/worker-install.sh, single-node/user-data
I changed some doc links, moved all references of the `v1.1.8_coreos.0` image to `v1.2.0_coreos.0`. Most importantly the kube-dns addon was updated to v11 which allows the v1.2.0 conformance tests to pass.
cc @aaronlevy
=> upgrade from v1.1.8 to v1.2.0

Documentation/deploy-master.md, Documentation/kubernetes-upgrade.md
cc @aaronlevy @robszumski @joshix 
Podmaster was removed in #355 because of the new `--leader-elect` flag. I updated the docs to reflect this.
=> Documentation: update docs for podmaster removal

multi-node/aws/pkg/cluster/cluster.go, multi-node/aws/pkg/config/config.go
There have been a lot of issues with people confused by the opaque
errors the AWS SDK outputs without this option.
Also, not using this option is marked deprecated anyway.
fixes #368
=> kube-aws: enable verbose credential chain errors

multi-node/aws/cmd/kube-aws/command_init.go, multi-node/aws/cmd/kube-aws/command_render.go, multi-node/aws/cmd/kube-aws/command_up.go
Before it wasn't entirely clear that the command had succeeded.  This
also clarifies if next steps are required or not, as well as makes them
easier to read.
Credit to robszumski for writing most of the messages.
fixes #353
=> kube-aws: improve success messages

.travis.yml
remove `go get golang.org/x/tools/cmd/vet`
=> kube-aws: fix travis build

multi-node/aws/pkg/config/region_map.go
Beta channel moved to `>962.0.0` on March 23, currently `991.2.0`.
=> kube-aws: Beta channel now supported by kube-aws

multi-node/aws/.gitignore, multi-node/aws/cmd/kube-aws/command_validate.go, multi-node/aws/pkg/cluster/cluster.go, multi-node/aws/pkg/cluster/cluster_test.go
=> kube-aws: validate that the key pair exists

multi-node/aws/pkg/config/templates/cloud-config-controller
=> kube-aws: increase heapster memory limit to 650Mi

multi-node/aws/cmd/kube-aws/command_validate.go, multi-node/aws/pkg/cluster/cluster.go
Info() never actually set the info.Name field to anything.
fixes #352
=> kube-aws: fix missing cluster-name in status cmd

multi-node/aws/pkg/cluster/cluster.go, multi-node/aws/pkg/cluster/cluster_test.go, multi-node/aws/pkg/config/config.go, multi-node/aws/pkg/config/config_test.go
Validate that recordSetTTL is positive, and that HostedZone is not
blank in config rather than cluster since they don't depend on any
external state.
fixes #400
=> kube-aws: set default recordSetTTL to 300

multi-node/aws/pkg/cluster/cluster_test.go, multi-node/aws/pkg/config/config.go
If you add the trailing dot to an empty hostname, the validation
that hostname isn't blank is worthless.
Basically none of the trailing dot stuff was being tested because it was
being added in ClusterFromFile rather than ClusterFromBytes, which is only
used in the live code. Also, the r53 dummy service was returning the
HostedZone and ResourceRecordSet without the final ., which would be
there in the real return values.
=> kube-aws: don't add trailing dot to empty dns names

multi-node/aws/pkg/cluster/cluster.go, multi-node/aws/pkg/cluster/cluster_test.go, multi-node/aws/pkg/config/config.go
We previously automatically appended trailing dots to externalDNSName
in the config struct, which was then reflected in kubeconfig.
This caused some problems with people using /etc/hosts, since they would
add the externalDNSName to their hosts file without the trailing dot,
and /etc/hosts lookups don't append one.
Now we only add trailing dots on the fly, whenever they're necessary to
interact with the AWS API, never anywhere persistent.
=> kube-aws: don't append trailing dot to externalDNSName

multi-node/aws/pkg/cluster/cluster.go, multi-node/aws/pkg/config/config.go, multi-node/aws/pkg/config/templates/cluster.yaml
Currently there is no way to specify tags to apply to the created cloudformation stack. Many companies use tags to audit their AWS environment and do cost analysis. This pull request adds the ability to specify cloudformation resource tags as a list of key-value pairs (string -> string) in the cluster.yaml file
=> kube-aws: cloudformation tags

multi-node/aws/pkg/config/templates/stack-template.json
Pods scheduled to worker instances can now access controller kubelet's read-only port on 10255. This is necessary now that controller kubelets are registered w/ the control plane.
Fixes #431
\cc @pbx0 @aaronlevy
=> kube-aws: allow access to controller kubelet's read-only port

multi-node/aws/cmd/kube-aws/command_init.go
If the cluster.yaml file exists and is longer than the new version being
written, the resulting cluster.yaml will contain portions of the previous
version. Open it with os.O_EXCL, causing an error if the file already
exists.
This replaces #425.
=> kube-aws: fail if configPath (cluster.yaml) already exists

single-node/Vagrantfile
Without this change, we would end up with a non-functional k8s cluster set up because of memory exhaustion.
Also made it configurable via a constant defined at top of Vagrantfile according to https://github.com/coreos/coreos-kubernetes/issues/311#issuecomment-199522832
Tested with Virtualbox running `vagrant destroy -f  && vagrant up` and after several minutes running `kubectl --kubeconfig kubeconfig get svc` to confirm it's really up.
Fixes #311
P.S. Just fixing around to decrease num of non-critial issues to make coreos-kubernetes looks really good as it actually is 😄
Thanks for sharing!
=> vagrant: Increase default Virtualbox memory to 2GB

multi-node/aws/cmd/kube-aws/command_destroy.go
Without this change, `kube-aws destroy` immediately returns with the message denoting that the cfn stack is already destroyed (which is not true as it takes several minutes until the stack get actually destroyed).
See https://github.com/coreos/coreos-kubernetes/issues/434#issuecomment-215514237 for discussion regarding phrasing and words.
Fixes #434
I have tested this change with:
Rebuilding the `kube-aws` executable, rendering a template and creating the cfn stack from it:
```
$ ./build
$ bin/kube-aws render
Error: mkdir credentials: file exists
$ rm -Rf credentials/ userdata/
$ bin/kube-aws render
Success! Stack rendered to stack-template.json.
Next steps:
1. (Optional) Validate your changes to cluster.yaml with "kube-aws validate"
2. (Optional) Further customize the cluster by …
```
=> kube-aws: Print clearer message on `kube-aws destroy`

multi-node/aws/pkg/config/templates/stack-template.json
Fixes #371
Tested with the following procedures:
```
$ cd multi-node/aws
$ ./build
$ bin/kube-aws --cluster-name kuoka-k8s *snip*
$ bin/kube-aws render
$ bin/kube-aws up --export
$ bin/kube-aws up
```
After the cfn stack created, seeing EC2 instance names prefixed with the cluster name:
=> kube-aws: prefix EC2 instance names with the cluster name

multi-node/aws/pkg/cluster/cluster.go
Error messages shouldn't end with punctuation.
Comment formatting for exported symbols.
cluster.ClusterInfo is redundant, rename to cluster.Info.
=> kube-aws: golint fixes

multi-node/aws/build, multi-node/aws/pkg/cluster/cluster.go, multi-node/aws/pkg/cluster/cluster_test.go
Previously you were only told which resources cloudformation failed to
create.  We now print the event details associated with each failure.
sample output:
fixes #430
=> kube-aws: Improve stack creation failed error messaging

Documentation/deploy-master.md, Documentation/deploy-workers.md, Documentation/getting-started.md, Documentation/kubernetes-networking.md, Documentation/kubernetes-on-aws.md, Documentation/kubernetes-on-baremetal.md, Documentation/kubernetes-on-vagrant.md, Documentation/kubernetes-upgrade.md, multi-node/aws/README.md, multi-node/aws/pkg/config/config.go, multi-node/aws/pkg/config/templates/cloud-config-controller, multi-node/aws/pkg/config/templates/cloud-config-worker, multi-node/aws/pkg/config/templates/cluster.yaml, multi-node/generic/controller-install.sh, multi-node/generic/worker-install.sh, single-node/user-data
I've been working on a change for the last few weeks to add support for Network Policy to this repo. The policy is implemented by Calico. Some information on what network policy is can be found [here](https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/NetworkPolicy.md)  and [here](https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/stars-demo/README.md)
The progression of the network policy API in kubernetes is being tracked at https://github.com/kubernetes/kubernetes/issues/22469
I'm aware that the CNI plugins aren't being downloaded in the best way - I'm currently waiting for a CNI release which should be happening very soon. I'll update the PR and retest as soon as binaries become available.
=> Add Kubernetes Network Policy

multi-node/aws/test
easier than always using ctrl+r
=> kube-aws: add script to run tests

multi-node/aws/build
https://github.com/koalaman/shellcheck
Quote variales to prevent word splitting/globbing.
Prefer $() to ``
Enable "strict mode": http://redsymbol.net/articles/unofficial-bash-strict-mode/
=> kube-aws: fix shellcheck warnings in build script

lib/init-ssl
Currently if a pod attempts to connect to kubernetes.default.svc using the ca
provided as a service account it will fail due to that name not being trusted
=> lib: Add kubernetes.default.svc as alt_name in openssl config

Documentation/kubernetes-on-vagrant.md
Fix a typo, add clarity of phrase.
Repair a code block that was not being rendered within a num list.
=> Documentation/kubernetes-on-vagrant: Fix typo and code block fmt

multi-node/aws/pkg/config/config.go, multi-node/aws/pkg/config/config_test.go, multi-node/aws/pkg/config/templates/cluster.yaml, multi-node/aws/pkg/config/templates/stack-template.json, multi-node/aws/pkg/config/tls_config_test.go, multi-node/aws/pkg/config/user_data_config_test.go
One step forward to achieve high-availability throughout the cluster.
This change allows you to specify multiple subnets in cluster.yaml to make workers' ASG spread instances over those subnets. Differentiating each subnet's availability zone results in H/A of workers.
Beware that this change itself does nothing with H/A of masters.
Possibly relates to #147, #100
I have tested this running `./build && rm -rf cluster.yaml userdata/ credentials/ && bin/kube-aws init *several options* && bin/kube-aws render && bin/kube-aws up` with with/without the newly added `subnets` section in `cluster.yaml`.
For example, given a `cluster.yaml`:
```yaml
*snip*
subnets:
- instanceCIDR: "10.0.0.0/24"
availabilityZone: ap-northeast-1a
- instanceCIDR: "10.0.1.0/24"
availabilityZone: ap-northeast-1c
```
After …
=> kube-aws: Support Multi-AZ workers on AWS

Documentation/deploy-master.md
Make the Nework Configuration list render on coreos.com.
Ref #495.
2. This section needs edits later for the Canal business (Flannel + Calico).
=> Documentation/deploy-master: Markdown fmt fixes

multi-node/aws/pkg/config/templates/stack-template.json
The whole file was using spaces for indentation except for a few
lines where tabs were used. Using spaces here keeps things also
visually consistent when a tab is not displayed as 8 spaces
=> `stack-template.json`: use spaces only for indenting

multi-node/aws/pkg/cluster/cluster.go, multi-node/aws/pkg/cluster/cluster_test.go, multi-node/aws/pkg/config/config.go, multi-node/aws/pkg/config/config_test.go, multi-node/aws/pkg/config/templates/cluster.yaml, multi-node/aws/pkg/config/templates/stack-template.json
Allows specifying a hosted zone by ID, in the case that multiple hosted zones exist with the same name
fixes #441 
WIP for now, \cc @cgag
=> kube-aws: hostedZoneId parameter

multi-node/aws/pkg/cluster/cluster_test.go, multi-node/aws/pkg/config/config.go
I have a kind-of-off-topic commit which introduces omitempty tags for the Cluster yaml fields. This is subtly desirable behavior I would think, in that defining an empty value in `cluster.yaml` should probably imply the preset default rather than empty.
Fixes bug 2 in #500
\cc @aaronlevy @michaeldiscala
=> Fix vpc validation for multiple subnets

Documentation/deploy-master.md, multi-node/aws/pkg/config/templates/cloud-config-controller, multi-node/generic/controller-install.sh, single-node/user-data
* Update to the k8s 1.2.0 recommended admission-control settings http://kubernetes.io/docs/admin/admission-controllers/
* Remove SecurityContextDeny. This resolved "ConfigMap [It] should be consumable from pods in volume..." conformance failures ([on bare metal](https://github.com/coreos/coreos-baremetal/issues/71#issuecomment-221932670))
* Closes coreos/coreos-kubernetes#497
@colhom @aaronlevy
=> *: Update apiserver admission-control

Documentation/deploy-master.md
Make it obvious which parts can be skipped if user does not want to use Calico 
(for example, if they are setting up the simplest possible test cluster).
=> docs: Mark parts to skip for no calico.

Documentation/deploy-workers.md
We haven't used the `${CONTROLER_IP}` anywhere else, and it wasn't introduced on the first page. Switch it to `${MASTER_HOST}` for consistency.
=> docs: fix up inconsistent variables

multi-node/aws/pkg/config/templates/stack-template.json
thanks @michaeldiscala for the bug report and fix.
\cc @cgag 
ref #500
=> stack-template: global scope for subnet routetableid

multi-node/aws/pkg/config/templates/cloud-config-controller, multi-node/aws/pkg/config/templates/cloud-config-worker
* Write out the encrypted certificate matter to /etc/kubernetes/ssl/*.pem.enc
* Decrypt contents to *.pem name that all of the components expect
Allows /opt/bin/decrypt-tls-assets to run more than once
Fixes #482
=> bug: guard against decrypting assets twice

multi-node/aws/pkg/config/templates/stack-template.json
ICMP doesn't use ports, it uses types and codes, when using ICMP setting toport and fromport to -1 allows all types and codes. 
fixes #526 
cc @colhom
=> kube-aws:  allow all ICMP traffic

Documentation/deploy-master.md
Correct fix from https://github.com/coreos/coreos-kubernetes/pull/539
https://quay.io/repository/coreos/hyperkube
=> docs: use correct hyperkube version tag

multi-node/aws/pkg/config/templates/cluster.yaml
stable is now the default in [v0.7.1](https://github.com/coreos/coreos-kubernetes/releases/tag/v0.7.1)
=> Update releaseChannel in cluster.yaml template

multi-node/aws/pkg/config/templates/cloud-config-worker
The controller [`kubelet.service`]( https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/templates/cloud-config-controller#L35) definition already does without an explicit dependency on docker.
Fixes #545
=> cloud-config-worker: kubelet.service no longer depends on docker.service

Documentation/kubernetes-on-aws-render.md
Missed a few things in the AWS guide when we updated the Calico process.
=> docs: update calico hyperkube instructions

multi-node/aws/pkg/cluster/cluster.go, multi-node/aws/pkg/cluster/cluster_test.go, multi-node/aws/pkg/config/config.go, multi-node/aws/pkg/config/config_test.go, multi-node/aws/pkg/config/templates/cluster.yaml, multi-node/aws/pkg/config/templates/stack-template.json
Uses General Purpose SSD `'gp2'` disks for worker and controller root volumes by default, but allows the user to choose a different volume type, such as the previously used `'standard'`, or `'io1'` for the provisioned IOPS SSD.
If the user set `'io1'` as the volume type, the code also ensures that the IOPS are set to a valid number.
Fixes #554
=> kube-aws: add optional root volume configs

Documentation/kubernetes-on-aws-launch.md
Text is expanding out of the page due to single backtick instead of triple.
=> docs: fix minor formatting error

multi-node/aws/cmd/kube-aws/command_up.go
Noticed this when I was running `kube-aws up`.
=> Typo fix in command_up.go

Documentation/deploy-addons.md
From https://github.com/coreos/coreos-baremetal/pull/274/commits/281e41159425e40bbca359c07773e511cccccfd0. Do coreos-kubernetes docs ever include screenshots? I've left it out for now.
@robszumski @aaronlevy 
Closes #576
=> Documentation: Add kube dashboard add-on docs

multi-node/aws/pkg/config/templates/cloud-config-controller, multi-node/aws/pkg/config/templates/cloud-config-worker, multi-node/generic/controller-install.sh, multi-node/generic/worker-install.sh, single-node/user-data
Overriding the 'ExecStart' to remove some environment variables will
break in CoreOS 1151.0.0 because Docker v1.12 will balk if given a
'daemon' argument to dockerd. We need to override the environment
variables set from an EnvironmentFile directive which requires another
EnvironmentFile directive. This way things will work with Docker v1.11
and Docker v1.12
=> all: make docker cni configuration flexible

Documentation/deploy-master.md, Documentation/deploy-workers.md, Documentation/kubernetes-on-aws-render.md, Documentation/kubernetes-on-generic-platforms.md
Directly linking to these and listing them out will make more folks get the install they are looking for. This also uses terms that folks are more apt to be looking for (`rbd`, `iscsi`).
Should land near https://github.com/coreos/coreos-kubernetes/pull/638
=> docs: mention optional config for all platforms (rdb, iscsi, etc)

multi-node/aws/pkg/config/templates/cloud-config-controller, multi-node/aws/pkg/config/templates/cloud-config-worker
decrypt-tls-assets runs `aws kms` in a docker container, and then
pipes the output to `base64`. This does not return a non-zero exit
code when decryption fails, and so the unit is not retried.
This commit adds an explicit test, forcing a non-zero exit code,
causing bash -e to barf.
=> Propagate aws kms decrypt's exit code in decrypt-tls-assets

Documentation/deploy-master.md, Documentation/deploy-workers.md, Documentation/kubelet-wrapper.md, multi-node/aws/pkg/config/templates/cloud-config-controller, multi-node/aws/pkg/config/templates/cloud-config-worker, multi-node/generic/controller-install.sh, multi-node/generic/worker-install.sh, single-node/user-data
The kubelet creates symlinks that capture the pod name, namespace, container name & Docker container ID to the Docker logs for pods in the `/var/log/containers` directory on the host.
By mapping the volume for this directory to the kubelet container by default, it becomes easier to use cluster level logging in Kubernetes, i.e., [fluentd-elasticsearch](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch), if the user choose to (see my comment in #320).
This PR updates both single-node and multi-node configurations.
(I should probably update some documentation as well, but first I want to know how you guys feel about this.)
=> Expose hosts' /var/log to the kubelet by default

multi-node/aws/pkg/config/templates/cloud-config-controller, multi-node/aws/pkg/config/templates/cloud-config-worker
fixes #545 
My investigation has found (at least on my reproductions) that `kubelet.service` failing for dependency reasons is caused by `decrypt-tls-assets.service` explicitly listing docker a dependency and failing for that reason.
I took this opportunity to switch us over to `rkt` for decrypting the TLS assets as well.
\cc @aaronlevy @robszumski @pbx0 @cgag
=> kube-aws: use rkt for decrypt-tls-assets

multi-node/aws/pkg/config/templates/cloud-config-controller, multi-node/aws/pkg/config/templates/cloud-config-worker
Fixes #676 
This passes conformance tests: https://jenkins.coreos.systems/view/Kubernetes/job/kubernetes-conformance-aws/131/consoleFull
\cc @crawford @pbx0 
`command: start` and `runtime: true` for all top-level services. 
The only things that are enabled are brought up as dependencies by systemd on behalf of other units (and have no command associated with them).
=> aws: top-level services are runtime: true

Documentation/deploy-master.md, Documentation/deploy-workers.md
I discovered that the Vagrant boxes have already been mounting resolv.conf into the kubelet-wrapper:
https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/generic/controller-install.sh#L95-L96
This PR brings the rest of the guides to parity.
fixes https://github.com/coreos/bugs/issues/1228 and https://github.com/coreos/coreos-kubernetes/issues/506
=> docs: mount resolv.conf from host

Documentation/kubernetes-on-aws-render.md
"This hostname be used to provision" to "This hostname *will* be used to provision"
=> docs: add missing word in external dns copy

Documentation/deploy-master.md, multi-node/aws/pkg/config/templates/cloud-config-controller, multi-node/generic/controller-install.sh, single-node/user-data
Update defaults to use recommended settings for v1.4.0
http://kubernetes.io/docs/admin/admission-controllers/
> For Kubernetes >= 1.4.0, we strongly recommend running the following set of admission control plug-ins (order matters):
--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
=> Update admission-control for 1.4.0

Documentation/deploy-workers.md
k8s/deploy-workers.md: Add "(optional)" to headers of optional sections
This is mainly so that it matches the deploy-master document. Setting up Calico is optional. As a newb, I had to go back to the master instructions and make sure that these parts were optional for the workers as well.
=> Mark sections as optional in deploy-workers.md

contrib/bump-version.sh
This fixes non-POSIX conformant usage of `expr` that is only supported
in the GNU/Linux variant and caused syntax errors on macOS 10.12.1.
=> contrib: fix bump-version script on macOS

Documentation/kubernetes-on-generic-platforms.md
> Hi guys. Broken link on https://coreos.com/kubernetes/docs/latest/kubernetes-on-generic-platforms.html to download worker-install.sh (https://coreos.com/kubernetes/docs/multi-node/generic/worker-install.sh)
This PR will reference these scripts on Github to 1) fix these links and 2) its probably better than serving shell scripts off of our domain.
=> docs: link to shell scripts on GH

Documentation/kubernetes-on-aws-launch.md
If you follow this guide, it will only provision a worker node and
controller node. In order to deploy 2 workers, you'd need to modify
workerCount in the cluster.yaml file before rendering the
CloudFormation template.
This commit corrects the output to what the user sees. Another question
is whether this guide should have users increase that value so their
sample deployment features > 1 worker.
=> docs: Remove extra instance deployment

Documentation/kubelet-wrapper.md
Rebased version of https://github.com/coreos/coreos-kubernetes/pull/684
cc @aaronlevy
=> docs: fix erroneous equals sign

Documentation/deploy-workers.md, Documentation/kubelet-wrapper.md, multi-node/aws/pkg/config/templates/cloud-config-controller, multi-node/aws/pkg/config/templates/cloud-config-worker, multi-node/generic/controller-install.sh, multi-node/generic/worker-install.sh, single-node/user-data
See discussion in https://github.com/coreos/coreos-overlay/pull/2230 and https://github.com/coreos/bugs/issues/1612 for why we want this.
This was all done by hand, so it's possible I made a dumb mistake somewhere (I hope not though).
I did check the multi-node/vagrant one worked as expected and that pods didn't pile up if I intentionally broke the kubelet cli
=> kubelet-wrapper: delete old pods on start

Documentation/deploy-master.md, Documentation/deploy-workers.md
There seem to be some updates to the scripts that are not covered in the Kubernetes Step by Step documentation. Updates documentation to add the changes that are applied in generic scripts folder.
Namely:
- flannel drop-in uses environment file /etc/kubernetes/cni/docker_opts_cni.env
- changes to the kubelet.service , which also require /opt/bin/host-rkt creation and /etc/kubernetes/cni folder artifacts
- kube-proxy annotation and dbus mount
- api-server livenessprobe
=> Docs: Sync Kubernetes step-by-step with generic scripts

Documentation/deploy-master.md, Documentation/deploy-workers.md, Documentation/kubernetes-on-vagrant-single.md, Documentation/kubernetes-on-vagrant.md, Documentation/kubernetes-upgrade.md, multi-node/generic/controller-install.sh, multi-node/generic/worker-install.sh, multi-node/vagrant/Vagrantfile, single-node/Vagrantfile, single-node/user-data
In order to get the hosted intall to work we had to make some changes to the deployment, the most disruptive being that we need to write to the hyperkubes `/opt/cni/bin` directory, so when Calico is enabled we mount that directory to the host.  Our calico/cni:v1.5.2 image deploys flannel, host-local, and loopback CNI binaries alongside the calico binaries.
Some other minor changes were:
- adding the pod-cidr to the proxy pods to get around some issues with Vagrant networking
- We use docker to run hyperkube with kubectl to deploy the calico.yaml manifest
- Removed all systemd Calico configuration
- Using one CNI conf for all nodes
- Vagrant files needed some touching as the VMs needed a bit more CPU/memory
We will want to update the remaining docs to use the same changes, but I wanted …
=> Updating Calico to hosted install

single-node/user-data
single-node/user-data: The calico.yaml needs to be created at /srv/kubernetes/manifests/calico.yaml instead of /etc/kubernetes/manifests/calico.yaml.
This is needed for the command `docker run --rm --net=host -v /srv/kubernetes/manifests:/host/manifests $HYPERKUBE_IMAGE_REPO:$K8S_VER /hyperkube kubectl apply -f /host/manifests/calico.yaml` to work. Without this change the above command fails and calico is not setup properly, and networking doesn't work at all.
=> change calico.yaml path from /etc to /srv

Documentation/kubernetes-on-baremetal.md
Upstream of dghubbe's https://github.com/coreos-inc/coreos-pages/pull/1241
Fix broken link to Ignition docs
Make links reference-style
=> Docs/kubernetes-on-baremetal: Rename baremetal to matchbox

Documentation/deploy-master.md, Documentation/deploy-workers.md, Documentation/kubelet-wrapper.md, Documentation/kubernetes-networking.md
Fixes #656
I'll file a followup to document the details of actually enabling kubelet authn/authz... but knowing is half the battle so we should have the note there until we have better docs.
=> kubelet: document that 10250 shouldn't be exposed

Documentation/deploy-master.md
"hostNetwork: true" mentioned twice in Kube controller manager static pod manifest. (duplicate key)
=> "hostNetwork: true mentioned twice"

Documentation/deploy-master.md, Documentation/deploy-workers.md, Documentation/kubelet-wrapper.md, Documentation/kubernetes-upgrade.md, multi-node/generic/controller-install.sh, multi-node/generic/worker-install.sh, single-node/user-data
This PR substitutes old deprecated variables used in kubelet-wrapper (RKT_OPTS, KUBELET_VERSION and KUBELET_ACI) to the new one.
=> Correct some docs variables

Documentation/kubernetes-networking.md
those ports have to be open on the master as well. otherwise things like kube-proxy+dashboard wont work.
=> missing ports for master
